---
- name: Modify verbose level on Job Templates
  hosts: all
  vars:
    verbosity: 0
    tower_host: '{{ lookup("env", "TOWER_HOST") }}'
    tower_username: '{{ lookup("env", "TOWER_USERNAME") }}'
    tower_oauthtoken: '{{ lookup("env", "TOWER_OAUTH_TOKEN") }}'
  tasks:

    - name: Get list of templates with verbosity greater than 0
      ansible.builtin.set_fact:
        jobs: "{{ query('ansible.tower.tower_api', 'job_templates', query_params={ 'verbosity__gt': '0' }), return_all=true | map(attribute='name') | list }}"
      run_once: true

    - name: Change verbose level
      ansible.tower.tower_job_template:
        name: "{{ item }}"
        verbosity: "{{ verbosity }}"
        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_oauthtoken: "{{ tower_oauthtoken }}"
      loop: "{{ jobs }}"
      run_once: true

